spring.application.name=dogshit
spring.datasource.url=postgresql://dpg-d7h9ov3bc2fs73cesir0-a.oregon-postgres.render.com/todos_db_ccuw?sslmode=${DB_SSL_MODE:disable}}
spring.datasource.username=todos_db_ccuw_user
spring.datasource.password=WuiM5l9fur7htey8B4eY0q3dgD61wdQ4
spring.datasource.driver-class-name=org.postgressql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format.sql=true

#todos_db