spring.application.name=dogshit
spring.datasource.url=${SPRING_DATASOURCEURL:jdbc:postgresal://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:todos_db}?sslmode=${DB_SSL_MODE:disable}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${DB_USERNAME:todos_user}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:todos_pass}}
spring.datasource.driver-class-name=org.postgressql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format.sql=true

#todos_db